const categories=["首页","国内","国际","科技","财经","AI","商业"];
const fallbackArticles=[{id:"welcome",category:"科技",title:"新闻数据正在首次更新",summary:"GitHub Actions 正在汇总最新报道，通常几分钟内完成。",source:"讯息流",language:"zh",publishedAt:null,url:"https://github.com/Cyrus-Qiu/news-hub/actions"}];
const signals=[["自动更新","系统","RSS 新闻源每 30 分钟同步一次","运行中"],["官方来源","国内","人民网、中国新闻网","已接入"],["国际来源","国际","BBC 中文、The Guardian","已接入"]];
let markets=[],articles=fallbackArticles,active="首页",query="",language="all",source="all",period="all",onlySaved=false,expanded=false,newsMeta={};const saved=new Set(JSON.parse(localStorage.getItem("news-hub-saved")||"[]"));
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
function safeUrl(value){try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.href:"#"}catch{return"#"}}
function timeAgo(value){if(!value)return"刚刚";const d=new Date(value),seconds=Math.floor((Date.now()-d)/1000);if(!Number.isFinite(seconds)||seconds<60)return"刚刚";if(seconds<3600)return`${Math.floor(seconds/60)} 分钟前`;if(seconds<86400)return`${Math.floor(seconds/3600)} 小时前`;if(seconds<604800)return`${Math.floor(seconds/86400)} 天前`;return d.toLocaleDateString("zh-CN")}
function tagOf(a){return a.category||a.tag||"综合"}
function focusArticle(){const weights={AI:5,财经:4,科技:3,国际:2,商业:2,国内:1};return [...articles].sort((a,b)=>{const age=x=>Math.max(0,(Date.now()-Date.parse(x.publishedAt||0))/36e5);return((weights[tagOf(b)]||0)-age(b)/12)-((weights[tagOf(a)]||0)-age(a)/12)})[0]||articles[0]}
function updateHero(){const article=focusArticle();if(!article)return;$("hero-title").textContent=article.title;$("hero-summary").textContent=article.summary||"点击查看原始媒体的完整报道。";$("hero-byline").textContent=`${article.source} · ${timeAgo(article.publishedAt)}`;const link=$("hero-link");link.href=safeUrl(article.url);link.target="_blank";link.rel="noopener noreferrer"}
function navButtons(target){target.innerHTML=categories.map(c=>`<button data-category="${c}" class="${c===active?"active":""}">${c}</button>`).join("");target.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{active=b.dataset.category;expanded=false;renderNavs();renderNews();if(target.id==="main-nav"&&active!=="首页")$("news").scrollIntoView({behavior:"smooth"})}))}
function renderNavs(){navButtons($("main-nav"));navButtons($("filter-nav"))}
function filtered(){const q=query.trim().toLowerCase(),now=Date.now(),maxAge=period==="6h"?216e5:period==="24h"?864e5:Infinity;return articles.filter(a=>(active==="首页"||tagOf(a)===active)&&(language==="all"||a.language===language)&&(source==="all"||a.source===source)&&(!onlySaved||saved.has(a.id))&&(now-Date.parse(a.publishedAt||0)<=maxAge)&&(!q||`${a.title}${a.summary||""}${tagOf(a)}${a.source}`.toLowerCase().includes(q)))}
function renderNews(){const all=filtered(),list=expanded?all:all.slice(0,12);$("section-title").textContent=active==="首页"?"把重要新闻，放在同一条信息流里":`${active} · 最新资讯`;$("result-count").textContent=`${all.length} 条结果`;$("news-grid").innerHTML=list.map(a=>{const id=escapeHtml(a.id),tag=escapeHtml(tagOf(a)),url=escapeHtml(safeUrl(a.url)),imageUrl=safeUrl(a.image||a.imageUrl||a.thumbnail||"");const visual=imageUrl==="#"?"":`<div class="visual news-image"><img src="${escapeHtml(imageUrl)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer"><span>${tag}</span></div>`;return`<article class="card">${visual}<div class="card-body"><div class="meta"><span>${escapeHtml(a.source)}</span><time>${escapeHtml(timeAgo(a.publishedAt))}</time></div><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.summary||"点击阅读全文，查看原始媒体报道。")}</p><div class="card-actions"><a class="read" href="${url}" target="_blank" rel="noopener noreferrer">阅读全文 ↗</a><button class="save ${saved.has(a.id)?"saved":""}" data-save="${id}">${saved.has(a.id)?"已收藏":"收藏"}</button></div></div></article>`}).join("");$("empty").hidden=all.length>0;$("load-more").hidden=expanded||all.length<=12;$("news-grid").querySelectorAll(".news-image img").forEach(img=>img.addEventListener("error",()=>img.closest(".news-image")?.remove(),{once:true}));$("news-grid").querySelectorAll("[data-save]").forEach(b=>b.addEventListener("click",()=>{saved.has(b.dataset.save)?saved.delete(b.dataset.save):saved.add(b.dataset.save);localStorage.setItem("news-hub-saved",JSON.stringify([...saved]));renderNews()}))}
function updateStatus(){const updated=new Date(newsMeta.updatedAt),valid=!Number.isNaN(updated.getTime()),sourceCount=newsMeta.sources?.length||0,status=valid?`更新于 ${updated.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})} · ${sourceCount} 个来源 · ${articles.length} 条`:"等待首次更新";const el=$("update-status");if(el)el.textContent=status;const live=$("live-status");if(live)live.lastChild.textContent=status}
function renderControls(){const sources=[...new Set(articles.map(a=>a.source))].sort();$("source-filter").innerHTML=`<option value="all">全部来源</option>${sources.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join("")}`;$("source-filter").value=source}
async function loadNews(){try{const response=await fetch(`data/news.json?v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(response.status);const data=await response.json();if(data.articles?.length)articles=data.articles;newsMeta=data}catch(error){console.warn("暂时无法读取新闻数据",error)}updateHero();renderControls();updateStatus();renderNews()}
$("signals").innerHTML=signals.map(s=>`<div class="signal-row"><time>${s[0]}</time><em>${s[1]}</em><strong>${s[2]}</strong><mark>${s[3]}</mark></div>`).join("");
function renderMarkets(){$("markets").innerHTML=markets.map(m=>{const value=Number(m.value),change=Number(m.changePercent),down=change<0;return`<div class="market-row ${down?"down":""}"><span>${escapeHtml(m.symbol||m.name)}</span><strong>${Number.isFinite(value)?value.toLocaleString("en-US",{maximumFractionDigits:2}):"—"}</strong><span class="spark"></span><b>${Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)}%`:"—"}</b></div>`}).join("")}
async function loadMarkets(){try{const response=await fetch(`data/markets.json?v=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(response.status);const data=await response.json();if(data.markets?.length)markets=data.markets}catch(error){console.warn("暂时无法读取市场数据",error)}renderMarkets()}
$("search-toggle").addEventListener("click",()=>{const p=$("search-panel"),opening=p.hidden;p.hidden=!opening;$("search-toggle").setAttribute("aria-expanded",String(opening));if(opening)$("search-input").focus()});
$("search-close").addEventListener("click",()=>{$("search-panel").hidden=true;$("search-toggle").setAttribute("aria-expanded","false")});
$("search-input").addEventListener("input",e=>{query=e.target.value;expanded=false;renderNews()});
$("language-filter").addEventListener("change",e=>{language=e.target.value;expanded=false;renderNews()});
$("source-filter").addEventListener("change",e=>{source=e.target.value;expanded=false;renderNews()});
$("period-filter").addEventListener("change",e=>{period=e.target.value;expanded=false;renderNews()});
$("saved-filter").addEventListener("click",()=>{const button=$("saved-filter");onlySaved=!onlySaved;button.classList.toggle("active",onlySaved);expanded=false;renderNews()});
$("load-more").addEventListener("click",()=>{expanded=true;renderNews()});
$("reset-filter").addEventListener("click",()=>{active="首页";query="";language=source=period="all";$("search-input").value="";["language-filter","source-filter","period-filter"].forEach(id=>$(id).value="all");renderNavs();renderNews()});
renderNavs();renderNews();loadNews();loadMarkets();
